#!/usr/bin/env python3
"""Native before/after evidence with a navigable comparison gallery."""
import json
from pathlib import Path
from compare_home import compose,Feature
root=Path(__file__).resolve().parents[2];batch=root/'qa/batch-05';folder=batch/'comparisons';folder.mkdir(parents=True,exist_ok=True)
features=[('lettering','C08','Lettering','classic-live.png'),('framing','C09','Photo framing','classic-live.png'),('video','C10','Video','room-live.png'),('made','C11','Made collection','classic-live.png'),('ticker','C12','Ticker','room-live.png'),('navigation','A01 / A06','One place to customize','room-live.png')]
rows=[]
for name,unit,title,file in features:
 rows.append(compose(root,batch/'before'/name/file,batch/'after'/name/file,folder/(name+'.png'),Feature(unit,title,name),390))
(folder/'manifest.json').write_text(json.dumps({'processing':'Native screenshots, equally scaled, no retouching/cropping.','baseline':'09b0baa; DEBUG entry routes only for matching lettering/framing/saved inputs.','comparisons':rows},indent=2)+'\n')
nav=''.join(f'<a href="#{name}">{unit} · {title}</a>' for name,unit,title,_ in features)
sections=''.join(f'<section id="{name}"><div class="caption"><span>{unit}</span><h2>{title}</h2><a href="{name}.png" target="_blank">Open full comparison ↗</a></div><img loading="lazy" src="{name}.png" alt="{title}: previous version on the left, updated version on the right"></section>' for name,unit,title,_ in features)
(folder/'index.html').write_text('''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tessera · Pass 05</title><style>
:root{color-scheme:dark}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#0b0e0d;color:#f0ebde;font:16px system-ui}header{max-width:1040px;padding:60px 28px 32px;margin:auto}header small,.caption>span{font:11px monospace;letter-spacing:2px;color:#c7ae7e}h1{font-size:clamp(32px,6vw,64px);letter-spacing:-2px;line-height:1.02;font-weight:550;margin:20px 0}p{max-width:740px;color:#adb2a8;line-height:1.6}nav{position:sticky;top:0;z-index:2;display:flex;overflow:auto;gap:8px;padding:14px max(18px,calc((100vw - 984px)/2));background:#151a17ed;backdrop-filter:blur(20px);border-block:1px solid #ffffff0d}a{color:inherit}nav a{flex:none;border:1px solid #ffffff21;border-radius:8px;padding:12px;text-decoration:none;font-size:13px}nav a:focus,nav a:hover{background:#c7ae7e;color:#10120f}main{max-width:1040px;padding:0 28px 60px;margin:auto}section{scroll-margin-top:96px;padding-top:38px;border-bottom:1px solid #ffffff1c}section img{display:block;width:100%;height:auto;margin:20px 0 32px}h2{font-size:28px;font-weight:500;letter-spacing:-.6px;margin:10px 0}.caption>a{font-size:12px;color:#adb2a8}footer{color:#adb2a8;font-size:13px;line-height:1.5;padding:24px 0}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}</style><header><small>TESSERA / PASS 05</small><h1>One place to<br>make it yours.</h1><p>Lettering, framing, films, saved creations and words in motion. Compare actual app captures from the previous and updated builds. Room customization now stays in the menu; artwork inspection remains a separate viewing task.</p></header><nav aria-label="Feature comparisons">'''+nav+'</nav><main>'+sections+'''<footer>Controlled QA artwork. Native screens are unretouched and scaled equally. Framing and lettering use matched content. Menu captures show their respective editing positions. RGB output was verified on the wall; physical LED colour and touch feel still need in-person review.</footer></main></html>''')
print(folder/'index.html')
