#!/usr/bin/env python3
"""Generate tessera/Tessera/PixelFont.swift from brain/art/pixelfont.py.

The wall and the phone must draw a letter identically, so the font has one
source and the Swift copy is generated from it rather than transcribed. Run
this after changing the Python font.

    .venv/bin/python tessera/Tools/gen_pixelfont.py
"""
import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, REPO)

from brain.art.pixelfont import FONT, ALIASES  # noqa: E402

OUT = os.path.join(REPO, "tessera", "Tessera", "PixelFont.swift")
# The earlier app keeps its own drawing helpers around the same table; only
# its table + normalize are generated, spliced between the markers below.
ALBUMWALL = os.path.join(REPO, "ios-companion", "AlbumWall", "PixelFont.swift")
AW_BEGIN = "    // BEGIN GENERATED by tessera/Tools/gen_pixelfont.py — do not hand-edit"
AW_END = "    // END GENERATED"

AW_TEMPLATE = '''
    static let glyphs: [Character: [UInt8]] = [
%(rows)s
    ]
    static let box: [UInt8] = [0x1F, 0x11, 0x11, 0x11, 0x11, 0x11, 0x1F]

    /// "<3" is how a heart gets typed. Case-sensitive, like the wall.
    static func normalize(_ text: String) -> String {
        var out = ""
        var skip = false
        let chars = Array(text)
        for (i, ch) in chars.enumerated() {
            if skip { skip = false; continue }
            if ch == "<", i + 1 < chars.count, chars[i + 1] == "3" {
                out.append("\\u{2665}")
                skip = true
            } else if let alias = aliases[ch] {
                out.append(alias)
            } else {
                out.append(ch)
            }
        }
        return out
    }

    private static let aliases: [Character: Character] = [%(aliases)s]
'''

HEADER = '''// The wall's handwriting, in Swift.
//
// GENERATED from brain/art/pixelfont.py by tessera/Tools/gen_pixelfont.py.
// Do not hand-edit: the whole point is that the phone and the wall render a
// letter identically. Regenerate when the Python font changes.
//
// Rows are 5-bit masks, bit 4 is the leftmost column. Case-sensitive, like
// the wall; an unknown character renders as a hollow box so a typo is
// visible instead of silently vanishing.

import Foundation

enum PixelFont {
    static let width = 5
    static let height = 7
    /// One blank column between glyphs.
    static let advance = 6

    static let box: [UInt8] = [0x1F, 0x11, 0x11, 0x11, 0x11, 0x11, 0x1F]

    static let glyphs: [Character: [UInt8]] = [
'''

FOOTER = '''    ]

    /// "<3" is how a heart gets typed.
    static func normalize(_ text: String) -> String {
        var out = ""
        var skip = false
        let chars = Array(text)
        for (i, ch) in chars.enumerated() {
            if skip { skip = false; continue }
            if ch == "<", i + 1 < chars.count, chars[i + 1] == "3" {
                out.append("\\u{2665}")
                skip = true
            } else if let alias = aliases[ch] {
                out.append(alias)
            } else {
                out.append(ch)
            }
        }
        return out
    }

    private static let aliases: [Character: Character] = [%(aliases)s]

    static func glyph(_ ch: Character) -> [UInt8] { glyphs[ch] ?? box }

    // ---- Hangul ----------------------------------------------------------
    // All 11,172 modern syllables plus the compatibility jamo, baked from
    // Galmuri7 (OFL) by Tools/gen_hangul.py: 7-row bitmasks, bit 6 leftmost,
    // 7 wide, advance 8, on the same baseline band as the ASCII glyphs.
    static let hangul: Data = {
        guard let url = Bundle.main.url(forResource: "Hangul7", withExtension: "bin"),
              let data = try? Data(contentsOf: url) else { return Data() }
        return data
    }()

    /// The rest of the world: cp -> (advance, dy, rows), parsed once from
    /// World7.bin. Baked by Tools/gen_worldfont.py from Galmuri7 and
    /// Misaki; kanji, kana, Greek, Cyrillic, accented Latin, punctuation.
    static let world: [UInt32: (advance: Int, dy: Int, rows: [UInt8])] = {
        guard let url = Bundle.main.url(forResource: "World7", withExtension: "bin"),
              let blob = try? Data(contentsOf: url) else { return [:] }
        var table: [UInt32: (Int, Int, [UInt8])] = [:]
        var i = blob.startIndex
        while i + 7 <= blob.endIndex {
            let cp = UInt32(blob[i]) << 24 | UInt32(blob[i + 1]) << 16
                   | UInt32(blob[i + 2]) << 8 | UInt32(blob[i + 3])
            let adv = Int(Int8(bitPattern: blob[i + 4]))
            let dy = Int(Int8(bitPattern: blob[i + 5]))
            let n = Int(blob[i + 6])
            i += 7
            guard i + n <= blob.endIndex else { break }
            table[cp] = (adv, dy, Array(blob[i..<(i + n)]))
            i += n
        }
        return table
    }()

    /// (rows, width, advance, dy) for any letterable character, else nil.
    static func cell(_ ch: Character) -> (rows: [UInt8], width: Int, advance: Int, dy: Int)? {
        if let rows = glyphs[ch] { return (rows, 5, 6, 0) }
        guard ch.unicodeScalars.count == 1,
              let scalar = ch.unicodeScalars.first else { return nil }
        let cp = Int(scalar.value)
        let off: Int
        if cp >= 0xAC00, cp <= 0xD7A3 {
            off = (cp - 0xAC00) * 7
        } else if cp >= 0x3131, cp <= 0x3163 {
            off = (11172 + cp - 0x3131) * 7
        } else {
            if let w = world[UInt32(cp)] { return (w.rows, 8, w.advance, w.dy) }
            return nil
        }
        guard hangul.count >= off + 7 else { return nil }
        return (Array(hangul[off..<(off + 7)]), 7, 8, 0)
    }

    /// Total width including the one-column gaps, both scripts.
    static func textWidth(_ text: String, scale: Int = 1) -> Int {
        var total = 0
        for ch in text { total += cell(ch)?.advance ?? 6 }
        return max(0, total - 1) * scale
    }

    /// Greedy wrap to a pixel width. A word wider than the whole line is
    /// broken hard, which is not a corner case here: Korean is usually
    /// written without spaces, so an entire lyric line can be one "word".
    static func wrap(_ text: String, maxWidth: Int, scale: Int) -> [String] {
        var lines: [String] = []
        var line = ""
        func hardBreak(_ word: String) -> String {
            var w = word
            while textWidth(w, scale: scale) > maxWidth, w.count > 1 {
                var k = 1
                while k < w.count,
                      textWidth(String(w.prefix(k + 1)), scale: scale) <= maxWidth {
                    k += 1
                }
                lines.append(String(w.prefix(k)))
                w = String(w.dropFirst(k))
            }
            return w
        }
        for word in text.split(separator: " ", omittingEmptySubsequences: false) {
            var word = String(word)
            if textWidth(word, scale: scale) > maxWidth {
                if !line.isEmpty { lines.append(line); line = "" }
                word = hardBreak(word)
            }
            let candidate = line.isEmpty ? word : line + " " + word
            if textWidth(candidate, scale: scale) <= maxWidth || line.isEmpty {
                line = candidate
            } else {
                lines.append(line)
                line = word
            }
        }
        if !line.isEmpty { lines.append(line) }
        return lines
    }
}
'''


def swift_key(ch: str) -> str:
    if ch == '"':
        return '"\\""'
    if ch == "\\":
        return '"\\\\"'
    return '"%s"' % ch


def main() -> None:
    rows = []
    seen = set()
    for ch, mask in FONT.items():
        if ch == "_BOX":
            continue
        # A Swift dictionary literal with a duplicate key traps at RUNTIME
        # ("Dictionary literal contains duplicate keys"), and a multi-char
        # key does not compile as Character — fail here, not on the phone.
        if len(ch) != 1:
            sys.exit(f"FONT key {ch!r} is not one character — fix pixelfont.py")
        key = swift_key(ch)
        if key in seen:
            sys.exit(f"FONT keys collide on Swift key {key} — fix pixelfont.py")
        seen.add(key)
        vals = ", ".join("0x%02X" % r for r in mask)
        rows.append("        %s: [%s]," % (key, vals))

    # "<" is handled by the "<3" rule in normalize, not as a plain alias
    alias_pairs = ", ".join(
        '"%s": "\\u{2665}"' % k for k in ALIASES if k != "<"
    )

    src = HEADER + "\n".join(rows) + "\n" + (FOOTER % {"aliases": alias_pairs})
    io.open(OUT, "w", encoding="utf8").write(src)
    print("wrote %s (%d glyphs)" % (os.path.relpath(OUT, REPO), len(FONT) - 1))

    with io.open(ALBUMWALL, encoding="utf8") as fh:
        aw = fh.read()
    b, e = aw.find(AW_BEGIN), aw.find(AW_END)
    if b == -1 or e == -1:
        sys.exit("markers missing in %s" % os.path.relpath(ALBUMWALL, REPO))
    region = AW_TEMPLATE % {"rows": "\n".join(rows), "aliases": alias_pairs}
    aw = aw[:b + len(AW_BEGIN)] + region + aw[e:]
    io.open(ALBUMWALL, "w", encoding="utf8").write(aw)
    print("wrote %s (same table)" % os.path.relpath(ALBUMWALL, REPO))


if __name__ == "__main__":
    main()
