/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as PowerRouteImport } from './routes/power'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SourcesRouteImport } from './routes/sources'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerRoute = PowerRouteImport.update({
  id: '/power',
  path: '/power',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/power': typeof PowerRoute
  '/profiles': typeof ProfilesRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/power': typeof PowerRoute
  '/profiles': typeof ProfilesRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/power': typeof PowerRoute
  '/profiles': typeof ProfilesRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/history' | '/power' | '/profiles' | '/settings' | '/sources'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/history' | '/power' | '/profiles' | '/settings' | '/sources'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/power'
    | '/profiles'
    | '/settings'
    | '/sources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  PowerRoute: typeof PowerRoute
  ProfilesRoute: typeof ProfilesRoute
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/power': {
      id: '/power'
      path: '/power'
      fullPath: '/power'
      preLoaderRoute: typeof PowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  PowerRoute: PowerRoute,
  ProfilesRoute: ProfilesRoute,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
